version: "3"

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-sql-db
    ports:
      - 1521:1521
      - 5500:5500
      - 2484:2484
    environment:
      ORACLE_PWD: P@ssword9
    volumes:
      - persist:/opt/oracle/oradata
      - ./startup/:/opt/oracle/scripts/startup

volumes:
  persist:
